### ISSUE TITLE
remove the edu.umd.cs.findbugs.annotations.NonNull;

### ISSUE THREAD

**Issue by treesong** [Torchmind/CIDRUtility#1]
I like this library! Could you remove the "edu.umd.cs.findbugs.annotations.NonNull;" or replace it with other findbugs lib?

**Comment by dotStart** [comment]
We're not really maintaining the library anymore at this point (potentially it may be migrated to Kotlin sometime in the future). Regardless, you may simply exclude said annotations in your dependency management tool as they are not read at runtime (which is why they were placed in the provided scope) meaning they do not need to be on the Class-Path.
